USE `consense`;

CREATE TABLE `Events` (
  `UID` INT NOT NULL,
  `StartDate` DATETIME NULL,
  `EndDate` DATETIME NULL,
  `Name` VARCHAR(200) NULL,
  `EventType` VARCHAR(200) NULL,
  `EventGroup` VARCHAR(200) NULL,
  `Comment` VARCHAR(200) NULL,
  PRIMARY KEY (`UID`))
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `Courses` (
  `UID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`UID`),
  UNIQUE INDEX (`Name` ASC))
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `Speakers` (
  `UID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`UID`),
  UNIQUE INDEX (`Name` ASC))
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `Rooms` (
  `UID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`UID`),
  UNIQUE INDEX (`Name` ASC))
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `EventToCourse` (
  `EventUID` INT NOT NULL,
  `CourseUID` INT NOT NULL,
  PRIMARY KEY (`EventUID`, `CourseUID`),
  INDEX (`CourseUID` ASC),
  CONSTRAINT 
    FOREIGN KEY (`EventUID`)
    REFERENCES `Events` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT
    FOREIGN KEY (`CourseUID`)
    REFERENCES `Courses` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `EventToSpeaker` (
  `EventUID` INT NOT NULL,
  `SpeakerUID` INT NOT NULL,
  PRIMARY KEY (`EventUID`, `SpeakerUID`),
  INDEX (`SpeakerUID` ASC),
  CONSTRAINT
    FOREIGN KEY (`EventUID`)
    REFERENCES `Events` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT
    FOREIGN KEY (`SpeakerUID`)
    REFERENCES `Speakers` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `EventToRoom` (
  `EventUID` INT NOT NULL,
  `RoomUID` INT NOT NULL,
  PRIMARY KEY (`EventUID`, `RoomUID`),
  INDEX (`RoomUID` ASC),
  CONSTRAINT
    FOREIGN KEY (`EventUID`)
    REFERENCES `Events` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT
    FOREIGN KEY (`RoomUID`)
    REFERENCES `Rooms` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `Users` (
  `UID` INT NOT NULL,
  `Name` VARCHAR(100) DEFAULT NULL,
  `CourseMatch` INT DEFAULT NULL,
  `SpeakerMatch` INT DEFAULT NULL,
  `RoomMatch` INT DEFAULT NULL,
  PRIMARY KEY (`UID`))
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `Sessions` (
  `UID` INT NOT NULL,
  `Token` VARCHAR(100) DEFAULT NULL,
  `Content` TEXT DEFAULT NULL,
  PRIMARY KEY (`UID`))
DEFAULT CHARACTER SET = utf8;